# fly.toml file generated for jwdkcf on 2023-01-04T11:30:51+05:30

app = "jwdkcf"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "54321"
  DATABASE_URL = "postgres://gst:qjTFHMfsSCasGESrJEvpou0oK4bVMvua@dpg-cep7pccgqg4ekmffv1vg-a.oregon-postgres.render.com/linkedin"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 54321
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"


  [[services.ports]]
    handlers = ["tls"]
    port = 443
  [services.ports.tls_options]
    alpn = ["h2"]

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
